name: Build ARM64 Python + xlwings on Rocky Linux 8 (using precompiled static Python)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable QEMU for ARM64
        run: |
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build Python + xlwings on Rocky Linux 8 ARM64
        run: |
          docker run --rm --platform linux/arm64 \
            -v $PWD:/workspace \
            -w /workspace \
            rockylinux:8 bash -c "\
              yum -y install wget tar && \
              wget https://github.com/astral-sh/python-build-standalone/releases/download/20251031/cpython-3.10.19+20251031-aarch64-unknown-linux-gnu-install_only_stripped.tar.gz && \
              tar xvzf cpython-3.10.19+20251031-aarch64-unknown-linux-gnu-install_only_stripped.tar.gz && mkdir download-pip && \
              python/bin/python3 -m pip download xlwings openpyxl pandas -d download-pip && \
              tar czf python-arm64-xlwings-pip.tar.gz download-pip \
            "

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-arm64-xlwings-pip
          path: python-arm64-xlwings-pip.tar.gz
